#!/usr/bin/env python3
import fileinput

in_code_block = False
for line in fileinput.input():
    if line.startswith('```'):
        print(line, end="")
        in_code_block = not in_code_block
    elif not in_code_block:
       length = 0
       words = line.split(" ")
       for i, word in enumerate(words):
           if length + len(word) > 80:
               print("\n%s" % word, end="")
               length = len(word) + 1
           else:
               if i == 0:
                   print("%s" % word, end="")
               else:
                   print(" %s" % word, end="")
               length = length + len(word) + 1
    else:
        print(line, end="")
